# Generated by Django 6.0 on 2026-01-13 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('duration', models.IntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lessons.students')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lessons.subjects')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lessons.teachers')),
            ],
        ),
    ]
