# Generated by Django 6.0 on 2026-01-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lessons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='lessons',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='lessons',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
